name: hts_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  # Python only - no R/PeacoQC
  - python>=3.10,<3.13
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - openpyxl
  - scipy
  - xlrd
  - pip
  # Pip packages
  - pip:
    - flowio

